version: '3'

services: 
  mongodb:
    image: mongo:latest
    ports:
      - 27017
    environment: 
      MONGO_INITDB_DATABSE: 'dokuin-api'
    volumes: 
      - mongodb_data_container:/data/db
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - './:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports: 
      - '4000:4000'
    depends_on: 
      - mongodb
    links: 
      - mongodb
  users:
    build: 
      context: ./services/users
      dockerfile: Dockerfile
    volumes: 
      - './services/users:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports: 
      - '3001:3001'
    depends_on: 
      - mongodb
    links: 
      - mongodb
  projects:
    build: 
      context: ./services/projects
      dockerfile: Dockerfile
    volumes: 
      - './services/projects:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports: 
      - '3002:3002'
    depends_on: 
      - mongodb
    links: 
      - mongodb
  documentations:
    build: 
      context: ./services/documentations
      dockerfile: Dockerfile
    volumes: 
      - './services/documentations:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports: 
      - '3003:3003'
    depends_on: 
      - mongodb
    links: 
      - mongodb

volumes:
  mongodb_data_container:
